var appConstants = {
  ADD_CUSTOMER: 'ADD_CUSTOMER',
  SELECT_CUSTOMER: 'SELECT_CUSTOMER',
  ADD_JOB: 'ADD_JOB',
  EDIT_JOB: 'EDIT_JOB',
  DELETE_JOB: 'DELETE_JOB',
  ADD_WORK_ENRTY: 'ADD_WORK_ENRTY',
  EDIT_WORK_ENTRY: 'EDIT_WORK_ENTRY',
  DELETE_WORK_ENTRY: 'DELETE_WORK_ENTRY',
  INITIAL_DATA: 'INITIAL_DATA',
  JOB_AND_WORK_TOGGLE: 'JOB_AND_WORK_TOGGLE'
};

module.exports = appConstants;
