var appConstants = {
  ADD_CUSTOMER: 'ADD_CUSTOMER',
  SELECT_CUSTOMER: 'SELECT_CUSTOMER',
  ADD_JOB: 'ADD_JOB',
  EDIT_JOB: 'EDIT_JOB',
  DELETE_JOB: 'DELETE_JOB',
  ADD_WORK_ENRTY: 'ADD_WORK_ENRTY',
  EDIT_WORK_ENTRY: 'EDIT_WORK_ENTRY',
  DELETE_WORK_ENTRY: 'DELETE_WORK_ENTRY',
  INITIAL_DATA: 'INITIAL_DATA',
  SAVE_INVOICE: 'SAVE_INVOICE',
  SELECT_INVOICE: 'SELECT_INVOICE',
  NEW_INVOICE: 'NEW_INVOICE',
  JOB_AND_WORK_TOGGLE: 'JOB_AND_WORK_TOGGLE',
  INVOICE_TOGGLE: 'INVOICE_TOGGLE'
};

module.exports = appConstants;
